# Spring boot settings
server:
  port: 8888
logging:
  level:
    com:
      fincons:
        itsle:
          rest: DEBUG

# Client credentials
auth:
  username: itsUser
  password: itsPassword

# Server base url
restful-server:
  url:
    base: http://localhost:8088/api/users
    auth: http://localhost:8088/authenticate